### PR TITLE
Added a custom middleware wrapper and added CORS config

### PR DESCRIPTION
**Pull request by craicoverflow**
## Motivation

JIRA: https://issues.jboss.org/browse/AEROGEAR-8388

## What

Created a custom middleware wrapper where we can use default middlewares and define our own.

## Why

We need a place to set, create and customize middleware. CORS is the first one that we are sure we will use.

## How

1. Added CORS config properties to config file.
2. Created a new package and file in `pkg/middlewares` called `middlewares.go`.
3. Referenced [Echo documentation](https://echo.labstack.com/middleware/cors) to "use" CORS middleware.

## Verification Steps
 
1. Update your `.env` file with the **ACCESS_CONTROL_ALLOW_X** properties in `.env.example`. You can also just let the config file use the default values.
2. Run the server: `go run cmd/mobile-security-service-server/main.go`
3. Make a request to the API using `curl`:

```sh
curl -H "Origin: http://example.com" \
  -H "Access-Control-Request-Method: GET" \
  -H "Access-Control-Request-Headers: X-Requested-With" \
  -X OPTIONS --verbose \
  http://localhost:3000 # Use the port your server is running on
```
 
4. Check the output:

```sh
< HTTP/1.1 204 No Content
< Access-Control-Allow-Headers: X-Requested-With
< Access-Control-Allow-Methods: GET
< Access-Control-Allow-Origin: *
```

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] Changes have been successfully verified by another team member 

## Progress

- [x] Finished task
- [ ] TODO

## Additional Notes

If you set the `ACCESS_CONTROL_ALLOW_ORIGIN` to a value other than "*" it won't show in the output of the curl command in step 4. This will need to be verified when we have the web application created.

### CODE REVIEW

**Comment by davidffrench** [comment]
Code changes look good to me, I have not had an opportunity to test it though.

**Comment by austincunningham** [comment]
code changes look good , don't like `package middlewares` as a name but that's my issue . Will test when I get a chance

**Comment by craicoverflow** [comment]
> code changes look good , don't like `package middlewares` as a name but that's my issue . Will test when I get a chance

Any suggestions? :smile:

**Comment by austincunningham** [comment]
> > code changes look good , don't like `package middlewares` as a name but that's my issue . Will test when I get a chance
> 
> Any suggestions?

`package middleware`

**Comment by austincunningham** [comment]
@craicoverflow My compiler don't like that change :(
```
cannot use middleware.CORSWithConfig(middleware.CORSConfig literal) (type "github.com/labstack/echo".MiddlewareFunc) as type "github.com/aerogear/mobile-security-service-server/vendor/github.com/labstack/echo".MiddlewareFunc in return argument
```

**Comment by austincunningham** [comment]
verified 
```
* Rebuilt URL to: http://localhost:3000/
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> OPTIONS / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.47.0
> Accept: */*
> Origin: http://example.com
> Access-Control-Request-Method: GET
> Access-Control-Request-Headers: X-Requested-With
> 
< HTTP/1.1 204 No Content
< Access-Control-Allow-Headers: X-Requested-With
< Access-Control-Allow-Methods: GET,HEAD,PUT,PATCH,POST,DELETE
< Access-Control-Allow-Origin: *
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< Date: Mon, 21 Jan 2019 12:30:12 GMT
< 
* Connection #0 to host localhost left intact
```

**Pull request merged**
